version: "2"
networks:
  eclipseworks-network:
    driver: bridge
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    networks:
      - eclipseworks-network
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=Eclipseworks@2024
      - MSSQL_SA_PASSWORD=Eclipseworks@2024
  eclipseworks:
    image: eclipseworks:latest
    build:
      context: .
      dockerfile: ./Eclipseworks.WebApi/Dockerfile
    ports:
      - 5000:5000
    networks:
      - eclipseworks-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./Eclipseworks.WebApi/appsettings.json:/app/appsettings.json
      - ./Eclipseworks.WebApi/appsettings.Docker.json:/app/appsettings.Docker.json
      - ./Eclipseworks.WebApi/appsettings.Development.json:/app/appsettings.Development.json
    depends_on:
      - sqlserver
  
